"""Render a quotation object to a Vitech-format PDF (fpdf2, no system deps).

The PDF is a faithful print of the deterministic quotation object built by
`quotation.build_quotation` — it adds no numbers of its own. Core PDF fonts are
latin-1 only, so text is sanitised to ASCII-safe glyphs and prices are written
"INR 25,50,000" (Indian grouping) rather than with a rupee symbol.
"""
from io import BytesIO

from fpdf import FPDF
from fpdf.enums import XPos, YPos

NAVY = (30, 58, 138)
ACCENT = (79, 110, 247)
LIGHT = (238, 242, 255)
GREY = (100, 116, 139)
TEXT = (15, 23, 42)
LINE = (210, 216, 228)

_MAP = {"–": "-", "—": "-", "•": "*", "→": "->",
        "₹": "INR ", "×": "x", "‘": "'", "’": "'",
        "“": '"', "”": '"', "…": "..."}


def _lat(s) -> str:
    s = str(s if s is not None else "")
    for a, b in _MAP.items():
        s = s.replace(a, b)
    return s.encode("latin-1", "replace").decode("latin-1")


def _inr(n) -> str:
    """Indian-grouped rupee amount, e.g. 2550000 -> 'INR 25,50,000'."""
    n = int(round(n or 0))
    neg, s = n < 0, str(abs(n))
    if len(s) <= 3:
        grp = s
    else:
        head, tail = s[:-3], s[-3:]
        parts = []
        while len(head) > 2:
            parts.insert(0, head[-2:])
            head = head[:-2]
        if head:
            parts.insert(0, head)
        grp = ",".join(parts) + "," + tail
    return ("-" if neg else "") + "INR " + grp


class _QPDF(FPDF):
    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(*GREY)
        self.cell(0, 5, _lat("Vitech Enviro Systems  -  budgetary draft, not a firm offer.  "
                             "Generated by the ATS Engineering Assistant."),
                  align="L")
        self.cell(0, 5, f"Page {self.page_no()}", align="R")


def _heading(pdf, text):
    pdf.ln(3)
    pdf.set_fill_color(*LIGHT)
    pdf.set_text_color(*NAVY)
    pdf.set_font("Helvetica", "B", 9.5)
    pdf.cell(0, 7, _lat("  " + text.upper()), border=0, fill=True,
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1.5)


def _row2(pdf, w1, t1, w2, t2, bold2=False, h=5.5):
    """A two-column row that wraps the right column and rules the bottom."""
    x, y0 = pdf.l_margin, pdf.get_y()
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*GREY)
    pdf.set_xy(x, y0)
    pdf.multi_cell(w1, h, _lat(t1), align="L")
    y1 = pdf.get_y()
    pdf.set_font("Helvetica", "B" if bold2 else "", 9)
    pdf.set_text_color(*TEXT)
    pdf.set_xy(x + w1, y0)
    pdf.multi_cell(w2, h, _lat(t2), align="L")
    y2 = pdf.get_y()
    yend = max(y1, y2)
    pdf.set_draw_color(*LINE)
    pdf.line(x, yend + 0.6, x + w1 + w2, yend + 0.6)
    pdf.set_xy(pdf.l_margin, yend + 1.6)


def render_quotation_pdf(quote: dict) -> bytes:
    q = quote or {}
    price = q.get("price") or {}
    pdf = _QPDF(format="A4")
    pdf.set_auto_page_break(True, margin=18)
    pdf.set_margins(15, 15, 15)
    pdf.add_page()
    usable = pdf.w - pdf.l_margin - pdf.r_margin  # ~180mm

    # ---- letterhead ----
    pdf.set_font("Helvetica", "B", 19)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 9, _lat("VITECH ENVIRO SYSTEMS"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 5, _lat("Air Pollution Control Equipment  -  Wet Scrubbers, Paint Booths, "
                        "Dust Collectors, Ovens"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)
    pdf.set_draw_color(*ACCENT)
    pdf.set_line_width(0.6)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + usable, pdf.get_y())
    pdf.set_line_width(0.2)
    pdf.ln(4)

    # ---- title band + ref/date + DRAFT ----
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*TEXT)
    pdf.cell(usable * 0.7, 8, _lat("BUDGETARY QUOTATION"), new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(217, 119, 6)
    pdf.cell(usable * 0.3, 8, _lat("DRAFT"), align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 5, _lat(f"Ref: {q.get('ref', '-')}        Date: {q.get('date', '-')}"),
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 6, _lat(q.get("headline", q.get("category_label", "Equipment"))),
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ---- given data ----
    given = q.get("given_data") or []
    if given:
        _heading(pdf, "Given data")
        for g in given:
            _row2(pdf, 70, g.get("label", ""), usable - 70, g.get("value", ""))

    # ---- technical scope (exclude requirement-echo rows) ----
    scope = [s for s in (q.get("scope") or []) if s.get("origin") != "given"]
    if scope:
        _heading(pdf, "Technical scope of supply")
        for s in scope:
            _row2(pdf, 70, s.get("item", ""), usable - 70, s.get("spec", ""))

    # ---- price schedule ----
    _heading(pdf, "Price schedule")
    qty = price.get("qty", 1)
    desc = q.get("headline", "System")
    _row2(pdf, 70, "Description", usable - 70, desc)
    if qty and qty > 1:
        _row2(pdf, 70, "Unit price (budgetary)", usable - 70, _inr(price.get("unit_price")))
        _row2(pdf, 70, "Quantity", usable - 70, f"{qty} nos")
    _row2(pdf, 70, "Order value (budgetary)", usable - 70, _inr(price.get("amount")), bold2=True)
    _row2(pdf, 70, "Indicative range", usable - 70,
          f"{_inr(price.get('range_low'))}  to  {_inr(price.get('range_high'))}")
    _row2(pdf, 70, "Confidence", usable - 70,
          f"{q.get('confidence_pct', '-')}%  ({q.get('confidence_label', '-')})")
    if price.get("currency") and price["currency"] != "INR":
        _row2(pdf, 70, "Currency", usable - 70, price["currency"])

    # ---- commercial terms ----
    terms = q.get("terms") or []
    if terms:
        _heading(pdf, "Commercial terms")
        pdf.set_font("Helvetica", "", 9)
        for t in terms:
            k = t[0] if len(t) > 0 else ""
            v = t[1] if len(t) > 1 else ""
            x, y0 = pdf.l_margin, pdf.get_y()
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*TEXT)
            pdf.set_xy(x, y0)
            pdf.multi_cell(40, 5.5, _lat(k), align="L")
            y1 = pdf.get_y()
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*GREY)
            pdf.set_xy(x + 40, y0)
            pdf.multi_cell(usable - 40, 5.5, _lat(v), align="L")
            pdf.set_xy(pdf.l_margin, max(y1, pdf.get_y()) + 0.8)

    # ---- basis + disclaimer ----
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*GREY)
    basis = q.get("basis_offers") or []
    if basis:
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(usable, 4.5, _lat("Priced from historical offers: " + ", ".join(basis)))
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(usable, 4.5, _lat(q.get("note",
                   "Budgetary estimate from historical offers - engineer to confirm.")))

    out = pdf.output()  # fpdf2 2.8 returns a bytearray
    return bytes(out) if isinstance(out, (bytearray, memoryview)) else out


if __name__ == "__main__":  # quick manual render for eyeballing
    sample = {
        "ref": "Q-TEST-DRAFT", "date": "02 Jul 2026",
        "headline": "Wet Scrubber - 800 CFM x 4", "category_label": "Wet Scrubber",
        "given_data": [{"label": "Air volume", "value": "800 CFM"},
                       {"label": "Tower diameter", "value": "750 mm"},
                       {"label": "Quantity", "value": "4"}],
        "scope": [{"item": "Chamber", "spec": "SS-304 2mm", "origin": "reused"},
                  {"item": "Spray nozzles", "spec": "17 nos SS-304", "origin": "rule"},
                  {"item": "Air volume", "spec": "800 CFM", "origin": "given"}],
        "price": {"amount": 2550000, "unit_price": 635000, "qty": 4,
                  "range_low": 2175000, "range_high": 2925000, "currency": "INR"},
        "terms": [["Prices", "Ex-works; GST extra as applicable."],
                  ["Validity", "30 days from date of offer."]],
        "confidence_pct": 75, "confidence_label": "Medium",
        "basis_offers": ["OFF-C2C-WS-178", "OFF-C2C-WS-20240921R1"],
        "note": "Budgetary draft - for engineer review before issue.",
    }
    with open("_sample_quote.pdf", "wb") as f:
        f.write(render_quotation_pdf(sample))
    print("wrote _sample_quote.pdf")
